### PR TITLE
Single video page and Watch History Feature

### LINKED ISSUE #6: Single Video Page

### LINKED ISSUE #13: Watch History Feature

### PR DESCRIPTION
**Pull request by romabulani**
Added below features:
- Single Video Page
- Integrating all pages with single video page
- CRUD operations on watch history
- Clear History Option
- Private routes
- Bug fixes of Playlist Management

[Deploy Preview](https://deploy-preview-12--bakinzone.netlify.app/)

### CODE REVIEW

**Review by lomesshh — APPROVED** [review]
- Code looks clean and modular
- great folder structure
- like that your are using barrel export in all folders
- like how you separated hooks in separate folder 

everything looks good to merge

**Review by shrey27 — APPROVED** [review]
code is very well structured especially using hooks
UI is working as expected
UI for Notes is also looking good

PR is ready to merge

**Review by manish591 — APPROVED** [review]
Your code is looking good to merge
I Really like: 
* Your import statement, they are looking very clean, I would also want to know how you had implemented this.
* Your code is very modular and properly structured, has consistent indentaion

Bugs In Your UI:
When I click on the liked tab, home and watch later all three are getting highlighted.

**Comment by romabulani** [comment]
> Your code is looking good to merge I Really like:
> 
> * Your import statement, they are looking very clean, I would also want to know how you had implemented this.
> * Your code is very modular and properly structured, has consistent indentaion
> 
> Bugs In Your UI: When I click on the liked tab, home and watch later all three are getting highlighted.

Thankyou Manish.
I have used barrel exports and absolute paths in my project. So, it reduces the import statements.

Regarding bugs, I have added the same path in all the 3 Navlinks as these features are yet to be implemented. Once done with all the features, it will be fixed.

**Comment by manish591** [comment]
> 

ok

**Pull request merged**
